name: voluntariado_app
description: Aplicación móvil para gestión de voluntariado
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  provider: ^6.0.5
  
  # HTTP Client
  http: ^1.1.0
  dio: ^5.3.3
  
  # Local Storage
  shared_preferences: ^2.2.2
  
  # UI
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  
  # Utils
  intl: ^0.18.1
  
  # Environment variables
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
    - assets/images/
    - assets/icons/

  # Fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf

